"""adding global discounts 

Revision ID: 01a8d4f83cff
Revises: 00641835890d
Create Date: 2025-10-21 17:07:10.526382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a8d4f83cff'
down_revision = '00641835890d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('max_uses', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('used_count', sa.Integer(), nullable=True))
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
        batch_op.alter_column('applicable_to',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('discounts', schema=None) as batch_op:
        batch_op.alter_column('applicable_to',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
        batch_op.drop_column('used_count')
        batch_op.drop_column('max_uses')
        batch_op.drop_column('description')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
