"""add verified field to payments

Revision ID: 5adf5aaf07fa
Revises: d2069c968056
Create Date: 2025-10-26 11:54:02.368374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5adf5aaf07fa'
down_revision = 'd2069c968056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('gateway_response', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('paystack_ref', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_metadata', sa.JSON(), nullable=True))
        batch_op.create_unique_constraint(None, ['paystack_ref'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('payment_metadata')
        batch_op.drop_column('paystack_ref')
        batch_op.drop_column('paid_at')
        batch_op.drop_column('gateway_response')
        batch_op.drop_column('verified')

    # ### end Alembic commands ###
