"""Fix contract template relationship

Revision ID: 00641835890d
Revises: 2a2855170672
Create Date: 2025-10-14 15:09:24.051076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00641835890d'
down_revision = '2a2855170672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('beat_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('contract_type', sa.String(length=50), nullable=False),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('contract_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['beat_id'], ['beats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_template_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'contract_templates', ['contract_template_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contracts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('contract_template_id')

    op.drop_table('contract_templates')
    # ### end Alembic commands ###
